//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpClientSample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string Guid { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> TimeBegin { get; set; }
    }
}
